name: Publish NPM

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Check for version change
        run: echo $(jq -r .version package.json) >> $GITHUB_STATE/version.txt
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v2
        with:
          access: public
          token: ${{ secrets.npm_token }}
        if: ${{ env.GITHUB_EVENT_NAME == 'push' && env.GITHUB_REF == 'refs/heads/master' && steps.version-check.outputs.version != env.GITHUB_STATE_BEFORE }}